#!/bin/sh
set -eu

log() { printf '%s\n' "$*"; }
warn() { printf '⚠️  %s\n' "$*" >&2; }

require_root() {
  if [ "$(id -u)" -ne 0 ]; then
    warn "请用 root 运行：sudo -i 或 su -"
    exit 1
  fi
}

read_nonempty() {
  # $1=prompt
  while :; do
    printf "%s" "$1"
    IFS= read -r v || true
    v="$(printf "%s" "$v" | tr -d '\r')"
    if [ -n "$v" ]; then
      printf "%s" "$v"
      return 0
    fi
    warn "不能为空，请重试。"
  done
}

ensure_line_in_file() {
  # $1=line $2=file
  line="$1"
  file="$2"
  touch "$file"
  if ! grep -Fqx "$line" "$file" 2>/dev/null; then
    echo "$line" >> "$file"
  fi
}

main() {
  require_root

  log "=== Alpine 初始化脚本开始 ==="

  # 1) Hostname
  log "\n[1/6] 设置 Hostname"
  HOSTNAME="$(read_nonempty '请输入 Hostname（例如 Alice）: ')"
  hostname "$HOSTNAME"
  echo "$HOSTNAME" > /etc/hostname
  ensure_line_in_file "127.0.0.1 $HOSTNAME" /etc/hosts
  log "✅ Hostname 已设置为：$HOSTNAME"

  # 2) 常用软件
  log "\n[2/6] 安装常用软件"
  apk add --no-cache ca-certificates vim curl wget iperf3 htop sing-box
  log "✅ 软件安装完成"

  # 3) DNS 修改并锁定
  log "\n[3/6] 设置 DNS 并锁定 /etc/resolv.conf"
  DNS_INPUT="$(read_nonempty '请输入 DNS（逗号分隔，例如 2606:4700:4700::1001,8.8.4.4）: ')"

  # 解锁（若之前被锁）
  if command -v chattr >/dev/null 2>&1; then
    chattr -i /etc/resolv.conf 2>/dev/null || true
  fi

  # 解析 DNS：逗号/空格都支持
  DNS_LIST="$(printf "%s" "$DNS_INPUT" | tr ', ' '\n\n' | sed '/^$/d')"

  # 写入 resolv.conf
  {
    echo "# Generated by init-alpine.sh"
    echo "# Do not edit if immutable flag is set."
    for ns in $DNS_LIST; do
      echo "nameserver $ns"
    done
  } > /etc/resolv.conf

  # 尝试锁定
  if ! command -v chattr >/dev/null 2>&1; then
    # chattr 在 Alpine 通常来自 e2fsprogs
    apk add --no-cache e2fsprogs >/dev/null 2>&1 || true
  fi

  if command -v chattr >/dev/null 2>&1; then
    chattr +i /etc/resolv.conf 2>/dev/null || warn "chattr 执行失败（可能非 ext 文件系统/容器 overlayfs），已跳过锁定。"
  else
    warn "系统无 chattr（且安装失败），已跳过锁定。"
  fi

  log "✅ DNS 已写入："
  cat /etc/resolv.conf

  # 4) 时区
  log "\n[4/6] 设置时区 Asia/Hong_Kong"
  ln -sf /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime
  echo "Asia/Hong_Kong" > /etc/timezone
  log "✅ 时区设置完成"

  # 5) 性能优化 sysctl
  log "\n[5/6] 写入性能优化到 /etc/sysctl.conf 并应用"
  cat > /etc/sysctl.conf <<'EOF'
# TCP 拥塞控制
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr

# 减少内存压力
vm.swappiness = 10
vm.vfs_cache_pressure = 200

# socket buffer（300M 足够）
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216

# TIME_WAIT 回收
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_tw_reuse = 1
EOF

  sysctl -p /etc/sysctl.conf || warn "sysctl -p 应用失败（某些内核/容器可能限制部分参数）。"
  log "✅ sysctl 已写入并尝试应用"

  # 6) BusyBox SSH -> OpenSSH
  log "\n[6/6] 安装并启用 OpenSSH，尽量停用 BusyBox SSH"
  apk update
  apk add --no-cache openssh openssh-server

  mkdir -p /etc/ssh
  # 生成主机密钥（无则生成）
  ssh-keygen -A 2>/dev/null || true

  # 加入开机自启
  rc-update add sshd default >/dev/null 2>&1 || true

  # 启动服务（OpenRC / 兼容方式）
  ( rc-service sshd start >/dev/null 2>&1 || service sshd start >/dev/null 2>&1 || true )

  # 尽量干掉 busybox sshd / dropbear（如果存在）
  ( pkill -f "busybox.*sshd" 2>/dev/null || true )
  ( pkill dropbear 2>/dev/null || true )

  log "✅ OpenSSH 已启用（已尝试停用 BusyBox SSH / dropbear）"

  log "\n=== 全部完成 ✅ ==="
  log "提示：如果你需要允许 root 远程登录/密码登录，请编辑 /etc/ssh/sshd_config（按你的安全策略）。"
}

main "$@"
