#!/bin/sh
set -eu

need_root() {
  if [ "$(id -u)" -ne 0 ]; then
    echo "❌ 请用 root 执行：sudo sh $0"
    exit 1
  fi
}

prompt() {
  # $1: message, $2: default(optional)
  msg="$1"
  def="${2:-}"
  if [ -n "$def" ]; then
    printf "%s (默认: %s): " "$msg" "$def"
  else
    printf "%s: " "$msg"
  fi
  read -r val || true
  if [ -z "${val:-}" ] && [ -n "$def" ]; then
    val="$def"
  fi
  echo "$val"
}

ensure_pkg() {
  # install packages if not exist (best-effort)
  apk add --no-cache "$@" >/dev/null
}

main() {
  need_root

  echo "== Alpine 初始化脚本 =="

  # 1) Hostname
  HOSTNAME="$(prompt '请输入 hostname' 'Alice')"
  echo "-> 设置 hostname: $HOSTNAME"
  hostname "$HOSTNAME"
  echo "$HOSTNAME" > /etc/hostname

  # 保证 /etc/hosts 里 127.0.0.1 对应 hostname（避免重复写入）
  if ! grep -qE "^127\.0\.0\.1[[:space:]]+$HOSTNAME([[:space:]]|$)" /etc/hosts 2>/dev/null; then
    echo "127.0.0.1 $HOSTNAME" >> /etc/hosts
  fi

  # 2) 安装常用软件
  echo "-> 安装常用软件"
  apk update >/dev/null
  apk add --no-cache ca-certificates vim curl wget iperf3 htop sing-box

  # 3) DNS 修改并锁定
  DNS_INPUT="$(prompt '请输入 DNS（逗号分隔，例如 2606:4700:4700::1001,8.8.4.4）' '2606:4700:4700::1001,8.8.4.4')"
  echo "-> 写入 /etc/resolv.conf"
  # 解析逗号分隔
  DNS_LIST="$(echo "$DNS_INPUT" | tr ',' ' ' | tr -s ' ')"

  # 尝试解锁（如果之前被锁）
  if command -v chattr >/dev/null 2>&1; then
    chattr -i /etc/resolv.conf 2>/dev/null || true
  fi

  {
    echo "# Generated by init script"
    for ns in $DNS_LIST; do
      ns="$(echo "$ns" | tr -d ' ')"
      [ -n "$ns" ] && echo "nameserver $ns"
    done
  } > /etc/resolv.conf

  # 锁定 resolv.conf（需要 chattr）
  if ! command -v chattr >/dev/null 2>&1; then
    echo "-> 未检测到 chattr，安装 e2fsprogs-extra 以支持 chattr +i"
    ensure_pkg e2fsprogs-extra
  fi
  if command -v chattr >/dev/null 2>&1; then
    chattr +i /etc/resolv.conf || true
  else
    echo "⚠️ chattr 不可用，已跳过锁定 /etc/resolv.conf"
  fi

  # 4) 时区
  echo "-> 设置时区 Asia/Hong_Kong"
  ln -sf /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime
  echo "Asia/Hong_Kong" > /etc/timezone

  # 5) 性能优化 sysctl
  echo "-> 写入 /etc/sysctl.conf 并应用"
  # 移除旧的同名项，避免重复/冲突（简单方式：先备份再覆盖为我们需要的块 + 原文件其它内容不保留）
  # 如果你想保留原有 sysctl.conf，改成追加模式即可。
  cp -a /etc/sysctl.conf "/etc/sysctl.conf.bak.$(date +%s)" 2>/dev/null || true

  cat > /etc/sysctl.conf <<'EOF'
# Generated by init script

# TCP 拥塞控制
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr

# 减少内存压力
vm.swappiness = 10
vm.vfs_cache_pressure = 200

# socket buffer（300M 足够）
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216

# TIME_WAIT 回收
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_tw_reuse = 1
EOF

  sysctl -p >/dev/null || {
    echo "⚠️ sysctl -p 执行失败（某些内核/容器可能不允许），你可以手动检查。"
  }

  # 6) 替换 BusyBox SSH 为 OpenSSH
  echo "-> 安装并启用 OpenSSH，停用 BusyBox SSH/Dropbear（若存在）"
  apk update >/dev/null
  apk add --no-cache openssh openssh-server

  mkdir -p /etc/ssh

  # 生成 host keys（如果没有）
  ssh-keygen -A >/dev/null 2>&1 || true

  # 启用服务
  rc-update add sshd default >/dev/null 2>&1 || true
  ( rc-service sshd start >/dev/null 2>&1 || service sshd start >/dev/null 2>&1 || true )

  # 尝试杀掉 busybox sshd / dropbear
  ( pkill -f "busybox.*sshd" 2>/dev/null || true )
  ( pkill dropbear 2>/dev/null || true )

  echo "✅ 初始化完成"
  echo "   - hostname: $HOSTNAME"
  echo "   - DNS: $DNS_INPUT"
  echo "   - timezone: Asia/Hong_Kong"
  echo "   - OpenSSH: 已尝试启用"
}

main "$@"
