#!/bin/sh
set -eu

need_root() {
  if [ "$(id -u)" != "0" ]; then
    echo "❌ 请用 root 运行（或 sudo）"
    exit 1
  fi
}

ask() {
  # $1 prompt, $2 default(optional)
  prompt="$1"
  def="${2:-}"
  if [ -n "$def" ]; then
    printf "%s [%s]: " "$prompt" "$def"
  else
    printf "%s: " "$prompt"
  fi
  read -r ans || true
  if [ -z "${ans:-}" ] && [ -n "$def" ]; then
    ans="$def"
  fi
  echo "$ans"
}

append_unique_line() {
  # $1 file, $2 exact line
  file="$1"
  line="$2"
  touch "$file"
  grep -Fqx "$line" "$file" 2>/dev/null || echo "$line" >> "$file"
}

replace_or_append_kv() {
  # $1 file, $2 key, $3 value  (key = value)
  file="$1"
  key="$2"
  val="$3"
  touch "$file"
  if grep -Eq "^[[:space:]]*${key}[[:space:]]*=" "$file"; then
    # 用 sed 原地替换
    sed -i "s#^[[:space:]]*${key}[[:space:]]*=.*#${key} = ${val}#g" "$file"
  else
    echo "${key} = ${val}" >> "$file"
  fi
}

print_step() {
  echo
  echo "========== $1 =========="
}

need_root

print_step "1) 设置 Hostname"
HOSTNAME="$(ask "请输入 hostname" "Alice")"

# set hostname immediately
hostname "$HOSTNAME" || true

# persist
echo "$HOSTNAME" > /etc/hostname

# hosts: 127.0.0.1 hostname
append_unique_line /etc/hosts "127.0.0.1 $HOSTNAME"

echo "✅ Hostname 已设置为: $HOSTNAME"

print_step "2) 安装常用软件"
apk add --no-cache ca-certificates vim curl wget iperf3 htop sing-box
echo "✅ 常用软件安装完成"

print_step "3) 设置 DNS 并锁定 /etc/resolv.conf"
DNS_INPUT="$(ask "请输入 DNS（逗号或空格分隔，如 2606:4700:4700::1001,8.8.4.4）" "2606:4700:4700::1001,8.8.4.4")"

# 解析 DNS 输入：逗号->空格，然后逐个取
DNS_LIST="$(echo "$DNS_INPUT" | tr ',' ' ' | tr -s ' ')"

# 写 resolv.conf（覆盖写入）
{
  echo "# Generated by init script on $(date 2>/dev/null || echo unknown-date)"
  for ns in $DNS_LIST; do
    [ -n "$ns" ] && echo "nameserver $ns"
  done
} > /etc/resolv.conf

# 尝试锁定（chattr 需要 e2fsprogs；某些文件系统不支持）
if command -v chattr >/dev/null 2>&1; then
  if chattr +i /etc/resolv.conf 2>/dev/null; then
    echo "✅ /etc/resolv.conf 已写入并 chattr +i 锁定"
  else
    echo "⚠️ chattr 存在但锁定失败（可能文件系统不支持 immutable）"
  fi
else
  echo "⚠️ 未找到 chattr（可选安装：apk add --no-cache e2fsprogs）"
  echo "   已写入 /etc/resolv.conf，但未锁定"
fi

print_step "4) 设置时区 Asia/Hong_Kong"
ln -sf /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime
echo "Asia/Hong_Kong" > /etc/timezone
echo "✅ 时区已设置为 Asia/Hong_Kong"

print_step "5) 性能优化 sysctl"
SYSCTL_FILE="/etc/sysctl.conf"
touch "$SYSCTL_FILE"

# TCP 拥塞控制
replace_or_append_kv "$SYSCTL_FILE" "net.core.default_qdisc" "fq"
replace_or_append_kv "$SYSCTL_FILE" "net.ipv4.tcp_congestion_control" "bbr"

# 减少内存压力
replace_or_append_kv "$SYSCTL_FILE" "vm.swappiness" "10"
replace_or_append_kv "$SYSCTL_FILE" "vm.vfs_cache_pressure" "200"

# socket buffer
replace_or_append_kv "$SYSCTL_FILE" "net.core.rmem_max" "16777216"
replace_or_append_kv "$SYSCTL_FILE" "net.core.wmem_max" "16777216"
# 这两条是三元组，按你给的值写整行（避免 kv 替换误伤）
if grep -Eq "^[[:space:]]*net\.ipv4\.tcp_rmem[[:space:]]*=" "$SYSCTL_FILE"; then
  sed -i "s#^[[:space:]]*net\.ipv4\.tcp_rmem[[:space:]]*=.*#net.ipv4.tcp_rmem = 4096 87380 16777216#g" "$SYSCTL_FILE"
else
  echo "net.ipv4.tcp_rmem = 4096 87380 16777216" >> "$SYSCTL_FILE"
fi
if grep -Eq "^[[:space:]]*net\.ipv4\.tcp_wmem[[:space:]]*=" "$SYSCTL_FILE"; then
  sed -i "s#^[[:space:]]*net\.ipv4\.tcp_wmem[[:space:]]*=.*#net.ipv4.tcp_wmem = 4096 65536 16777216#g" "$SYSCTL_FILE"
else
  echo "net.ipv4.tcp_wmem = 4096 65536 16777216" >> "$SYSCTL_FILE"
fi

# TIME_WAIT 回收
replace_or_append_kv "$SYSCTL_FILE" "net.ipv4.tcp_fin_timeout" "15"
replace_or_append_kv "$SYSCTL_FILE" "net.ipv4.tcp_tw_reuse" "1"

# 应用
sysctl -p || true
echo "✅ sysctl 已写入并尝试应用（sysctl -p）"

print_step "6) 用 OpenSSH 替换 BusyBox SSH"
apk update
apk add --no-cache openssh openssh-server

mkdir -p /etc/ssh

# 生成 host keys（只要缺就生成）
ssh-keygen -A

# 启用并启动 sshd（OpenRC / service 兼容）
if command -v rc-update >/dev/null 2>&1; then
  rc-update add sshd default || true
fi

( rc-service sshd restart 2>/dev/null || rc-service sshd start 2>/dev/null || service sshd start 2>/dev/null || /etc/init.d/sshd start 2>/dev/null || true )

# 尝试停掉 busybox sshd/dropbear
( pkill -f "busybox.*sshd" 2>/dev/null || true )
( pkill dropbear 2>/dev/null || true )

echo "✅ OpenSSH 已启用（已尝试启动），BusyBox SSH / dropbear 已尝试停用"

echo
echo "🎉 全部完成。建议你检查："
echo " - hostname: $(hostname 2>/dev/null || echo "$HOSTNAME")"
echo " - resolv.conf: cat /etc/resolv.conf"
echo " - sshd: ps | grep sshd"
